// Generated by CoffeeScript 1.6.3
(function() {
  "use strict";
  module.exports = function(grunt) {
    var getTasksArr;
    grunt.registerTask("generateJsDoc", ["clean:jsdoc", "jsdoc"]);
    grunt.registerTask("generateYuiDoc", ["clean:yuidoc", "yuidoc"]);
    grunt.task.registerTask("uncssTest", "A sample task that logs stuff.", function(arg) {
      if (arguments.length === 0) {
        return grunt.log.writeln(this.name + ", no args");
      } else {
        arg = arg != null ? arg : '';
        if (arg === "formal") {
          arg = "";
        }
        grunt.config.set('state', arg);
        grunt.log.writeln(grunt.config.get('state'));
        return grunt.task.run(['clean', 'useminPrepare', "copy", "requirejs", "uglify", 'uncss', "autoprefixer", 'imagemin', 'htmlmin:usemin', "htmlrefs", "regex-replace", 'rev', 'usemin', "htmlmin:navi", 'manifest:generate', "compress"]);
      }
    });
    getTasksArr = function() {
      var arr;
      return arr = ["regex-replace", 'rev', 'usemin', "htmlmin:navi", 'manifest:generate'];
    };
    return grunt.task.registerTask('default', 'execute tasks by param by grunt cli', function(arg, arg1) {
      return grunt.executeCustomTasks(arg, arg1, getTasksArr());
    });
  };

}).call(this);

/*
//@ sourceMappingURL=tasks.map
*/
