// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  define([], function() {
    if ($.isEmptyObject(mapHandler.curInfo) || $.isEmptyObject(mapHandler.shareInfo) || Number(mapHandler.shareInfo.source) !== 2) {
      return;
    }
    return $('#icon_request_path').trigger('touchstart');
  });

}).call(this);

/*
//@ sourceMappingURL=share-path.map
*/
